allowBuilds:
  esbuild: true
  grpc: true
  sharp: true
  supabase: true
  unrs-resolver: true
packages:
  - 'packages/*'
patchedDependencies:
  spawn-command@0.0.2: patches/spawn-command@0.0.2.patch
